### PR TITLE
Update

### PR DESCRIPTION
**Pull request by Vinyl-Davyl**

### CODE REVIEW

**Comment by Olanetsoft** [comment]
Fix conflict @Vinyl-Davyl

**Comment by Vinyl-Davyl** [comment]
@Olanetsoft Conflict resolved already.

Nice working with you!

**Comment by Vinyl-Davyl** [comment]
Had to make an update to reduce one of the cases missed in last PR

**Comment by Olanetsoft** [comment]
Thanks for your contribution @Vinyl-Davyl

**Pull request merged**
